profiles_settings: 
  user: 'netmining'
  install_node: '0.12.7' 
  path: '/opt/settings'
  source: 'ssh://git@stash.ignitionone.com:7999/ui/settings.git'
  branch: 'master'
# git_tag: 'IONEREL-2978'
  owner: 'netmining'
  group: 'netmining'
  mode: '775'
  node_env: 'PROD'
  lang: 'en_US.UTF-8'
  aws_access_key_id: 'AKIAIQFCW7J3OPM5SQUA'
  aws_secret_access_key: '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' 
  
profiles_analytics: 
  user: 'netmining'
  install_node: '0.12.7' 
  path: '/opt/analytics-report-builder'
  source: 'ssh://git@stash.ignitionone.com:7999/ui/analytics-report-builder.git'
  branch: 'master'
# git_tag: 'IONEREL-2978'
  owner: 'netmining'
  group: 'netmining'
  mode: '775'
  node_env: 'PROD'
  lang: 'en_US.UTF-8'
  aws_access_key_id: 'AKIAIQFCW7J3OPM5SQUA'
  aws_secret_access_key: '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'

